global using AutoMapper;
global using SalasDeEnsayo.DTOs;
global using SalasDeEnsayo.Entidades;
global using FluentValidation;
global using Microsoft.AspNetCore.Mvc;
global using SalasDeEnsayo.Infraestructura;
global using Microsoft.AspNetCore.RateLimiting;
global using Microsoft.EntityFrameworkCore;
global using SalasDeEnsayo.Interfaces;