// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalasDeEnsayo.Infraestructura;

#nullable disable

namespace SalasDeEnsayo.Infraestructura.Migraciones
{
    [DbContext(typeof(AppDbContext))]
<<<<<<< HEAD:SalasDeEnsayo/Infraestructura/Migraciones/20230615164356_add listaprecio2.Designer.cs
    [Migration("20230615164356_add listaprecio2")]
    partial class addlistaprecio2
=======
    [Migration("20230616124709_20230616 0946")]
    partial class _202306160946
>>>>>>> 0425b26e3dbd324ba73832f131ec632d3399901a:SalasDeEnsayo/Infraestructura/Migraciones/20230616124709_20230616 0946.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD:SalasDeEnsayo/Infraestructura/Migraciones/20230615164356_add listaprecio2.Designer.cs
            modelBuilder.Entity("SalasDeEnsayo.Entidades.listadeprecio", b =>
=======
            modelBuilder.Entity("SalasDeEnsayo.Entidades.reserva", b =>
>>>>>>> 0425b26e3dbd324ba73832f131ec632d3399901a:SalasDeEnsayo/Infraestructura/Migraciones/20230616124709_20230616 0946.Designer.cs
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

<<<<<<< HEAD:SalasDeEnsayo/Infraestructura/Migraciones/20230615164356_add listaprecio2.Designer.cs
                    b.Property<string>("dia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<long>("precioxhora")
                        .HasColumnType("bigint");

                    b.Property<int>("tiposalaid")
=======
                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("salaDeEnsayoId")
>>>>>>> 0425b26e3dbd324ba73832f131ec632d3399901a:SalasDeEnsayo/Infraestructura/Migraciones/20230616124709_20230616 0946.Designer.cs
                        .HasColumnType("int");

                    b.HasKey("id");

<<<<<<< HEAD:SalasDeEnsayo/Infraestructura/Migraciones/20230615164356_add listaprecio2.Designer.cs
                    b.HasIndex("tiposalaid");

                    b.ToTable("listadeprecio");
=======
                    b.HasIndex("salaDeEnsayoId");

                    b.ToTable("reserva");
>>>>>>> 0425b26e3dbd324ba73832f131ec632d3399901a:SalasDeEnsayo/Infraestructura/Migraciones/20230616124709_20230616 0946.Designer.cs
                });

            modelBuilder.Entity("SalasDeEnsayo.Entidades.saladeensayo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("descripcion_sala");

                    b.Property<bool>("habilitado")
                        .HasColumnType("bit");

                    b.Property<int>("tipodesalaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tipodesalaid");

                    b.ToTable("saladeensayo");
                });

            modelBuilder.Entity("SalasDeEnsayo.Entidades.tipodesala", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<bool>("habilitado")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("tipodesala");
                });

<<<<<<< HEAD:SalasDeEnsayo/Infraestructura/Migraciones/20230615164356_add listaprecio2.Designer.cs
            modelBuilder.Entity("SalasDeEnsayo.Entidades.listadeprecio", b =>
                {
                    b.HasOne("SalasDeEnsayo.Entidades.tipodesala", "tiposala")
                        .WithMany("listadeprecios")
                        .HasForeignKey("tiposalaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tiposala");
=======
            modelBuilder.Entity("SalasDeEnsayo.Entidades.reserva", b =>
                {
                    b.HasOne("SalasDeEnsayo.Entidades.saladeensayo", "salaDeEnsayo")
                        .WithMany("reservas")
                        .HasForeignKey("salaDeEnsayoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("salaDeEnsayo");
>>>>>>> 0425b26e3dbd324ba73832f131ec632d3399901a:SalasDeEnsayo/Infraestructura/Migraciones/20230616124709_20230616 0946.Designer.cs
                });

            modelBuilder.Entity("SalasDeEnsayo.Entidades.saladeensayo", b =>
                {
                    b.HasOne("SalasDeEnsayo.Entidades.tipodesala", "tipo")
                        .WithMany("saladeensayos")
                        .HasForeignKey("tipodesalaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipo");
                });

<<<<<<< HEAD:SalasDeEnsayo/Infraestructura/Migraciones/20230615164356_add listaprecio2.Designer.cs
            modelBuilder.Entity("SalasDeEnsayo.Entidades.tipodesala", b =>
                {
                    b.Navigation("listadeprecios");

=======
            modelBuilder.Entity("SalasDeEnsayo.Entidades.saladeensayo", b =>
                {
                    b.Navigation("reservas");
                });

            modelBuilder.Entity("SalasDeEnsayo.Entidades.tipodesala", b =>
                {
>>>>>>> 0425b26e3dbd324ba73832f131ec632d3399901a:SalasDeEnsayo/Infraestructura/Migraciones/20230616124709_20230616 0946.Designer.cs
                    b.Navigation("saladeensayos");
                });
#pragma warning restore 612, 618
        }
    }
}
